// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";

function includeStyles(param) {
  CssJs.$$global("html, body, #root", [
        CssJs.padding(CssJs.zero),
        CssJs.margin(CssJs.zero),
        CssJs.fontSize(CssJs.px(10))
      ]);
  return CssJs.$$global("button", [CssJs.cursor(CssJs.pointer)]);
}

export {
  includeStyles ,
  
}
/* CssJs Not a pure module */
