// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Button(Props) {
  var children = Props.children;
  return React.createElement("button", undefined, children);
}

var make = Button;

export {
  make ,
  
}
/* react Not a pure module */
