// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button from "./components/Button/Button.bs.js";
import * as Render from "./lib/Render.bs.js";

function App(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement(Button.make, {
                  children: Render.s("Click")
                }));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
